import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import QueryProvider from '@shared/components/providers/QueryProvider';
import type { Metadata } from 'next';
import '../styles/globals.css';
import React from 'react';

import { lexend } from '../shared/components/lib/Font';
import MuiThemeProvider from '../shared/components/lib/MuiThemeProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lexend.className} font-sans`}>
        <AppRouterCacheProvider>
          <MuiThemeProvider>
            <QueryProvider>{children}</QueryProvider>
          </MuiThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
