import type { Metadata } from 'next';
import localFont from 'next/font/local';
import '../app/globals.css';

const lexend = localFont({
  src: [
    {
      path: '../public/fonts/lexend-latin-400-normal.woff',
      weight: '400', // 👈 set font weight here
      style: 'normal', // 👈 set style (normal/italic)
    },
    {
      path: '../public/fonts/lexend-latin-500-normal.woff',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../public/fonts/lexend-latin-700-normal.woff',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../public/fonts/lexend-latin-900-normal.woff',
      weight: '900', // 👈 set font weight here
      style: 'normal', // 👈 set style (normal/italic)
    },
  ],
  variable: '--font-lexend',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lexend.className} font-sans`}>{children}</body>
    </html>
  );
}
